[run]
  deadline = "2m"
  skip-files = []

[linters-settings]

  [linters-settings.govet]
    check-shadowing = true

  [linters-settings.gocyclo]
    min-complexity = 12.0

  [linters-settings.maligned]
    suggest-new = true

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 3.0

  [linters-settings.misspell]
    locale = "US"

[linters]
  enable-all = true
  disable = [
    "maligned",
    "lll",
    "dupl",
    "wsl",
    "gomnd",
    "goerr113",
    "testpackage",
  ]

[issues]
  exclude-use-default = false
  max-per-linter = 0
  max-same-issues = 0
  exclude = ["G306"]
  [[issues.exclude-rules]]
    path = "version.go"
    text = "`(version|date|commit)` is a global variable"
  [[issues.exclude-rules]]
    path = "fixtures_test.go"
    text = "`(sampleMain|sampleGoMod|sampleGoMod20)` is a global variable"

  [[issues.exclude-rules]]
    path = "upgrader.go"
    text = "cognitive complexity (\\d+) of func `update` is high"
