version: "2"

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true

linters:
  default: all
  disable:
    - cyclop # duplicate of gocyclo
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - lll
    - makezero
    - mnd
    - nlreturn
    - noctx
    - paralleltest
    - rowserrcheck # not relevant (SQL)
    - sqlclosecheck # not relevant (SQL)
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/instana/testify
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    forbidigo:
      forbid:
        - pattern: ^print(ln)?$
        - pattern: ^panic$
        - pattern: ^spew\.Print(f|ln)?$
        - pattern: ^spew\.Dump$
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - unnamedResult
        - sloppyReassign
        - rangeValCopy
        - octalLiteral
        - paramTypeCombine # already handle by gofumpt.extra-rules
      enabled-tags:
        - diagnostic
        - style
        - performance
      settings:
        hugeParam:
          sizeThreshold: 100
    gocyclo:
      min-complexity: 14
    godox:
      keywords:
        - FIXME
    gosec:
      excludes:
        - G306
        - G304
    govet:
      enable:
        - shadow
    misspell:
      locale: US
    perfsprint:
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: false
  exclusions:
    rules:
      - linters:
          - funlen
        path: (.+)_test.go
      - path: version.go
        text: (version|date|commit) is a global variable
      - path: fixtures_test.go
        text: (sampleMain20|sampleGoMod20) is a global variable
      - path: upgrader.go
        text: cognitive complexity (\d+) of func `updatePackages` is high
      - path: (.+)\.go$
        text: 'package-comments: should have a package comment'

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
