run:
  timeout: 2m
  skip-files: []

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 14
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  gofumpt:
    extra-rules: true
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  godox:
    keywords:
      - FIXME
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
    settings:
      hugeParam:
        sizeThreshold: 100
  forbidigo:
    forbid:
      - '^print(ln)?$'
      - '^panic$'
      - '^spew\.Print(f|ln)?$'
      - '^spew\.Dump$'
  gosec:
    excludes:
      - G306
      - G304

linters:
  enable-all: true
  disable:
    - scopelint # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - golint # deprecated
    - exhaustivestruct # deprecated
    - scopelint # deprecated
    - varcheck # deprecated
    - structcheck # deprecated
    - nosnakecase # deprecated
    - deadcode # deprecated
    - ifshort # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - dupl
    - wsl
    - nlreturn
    - gomnd
    - goerr113
    - wrapcheck
    - testpackage
    - paralleltest
    - tparallel
    - noctx
    - exhaustive
    - exhaustruct
    - makezero
    - varnamelen

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'package-comments: should have a package comment'
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
    - path: version.go
      text: (version|date|commit) is a global variable
    - path: fixtures_test.go
      text: (sampleMain20|sampleGoMod20) is a global variable
    - path: upgrader.go
      text: cognitive complexity (\d+) of func `updatePackages` is high
    - linters: [ perfsprint ]
      text: 'fmt.Sprintf can be replaced with string'
