version: 2

project_name: motoko

builds:
  - binary: motoko
    env:
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
#      - freebsd
#      - openbsd
#    goarch:
#      - amd64
#      - 386
#      - arm
#      - arm64
#    goarm:
#      - 7
#      - 6
#      - 5
#
#    ignore:
#      - goos: darwin
#        goarch: 386
#      - goos: openbsd
#        goarch: arm
#      - goos: freebsd
#        goarch: arm

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^test:'
      - '^tests:'

archives:
  - id: motoko
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm}}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

source:
  enabled: true
  name_template: '{{ .ProjectName }}-v{{ .Version }}-source'

#brews:
#  - repository:
#      owner: ldez
#      name: homebrew-tap
#    commit_author:
#      name: ldez
#      email: ldez@users.noreply.github.com
#    directory: Formula
#    homepage: https://github.com/ldez/motoko
#    description: Based on Go modules, update a dependency to a major version
#    test: |
#      system "#{bin}/motoko version"
#
#scoops:
#  - repository:
#      owner: ldez
#      name: scoop-bucket
#    commit_author:
#      name: ldez
#      email: ldez@users.noreply.github.com
#    homepage: https://github.com/ldez/motoko
#    description: Based on Go modules, update a dependency to a major version.
#    license: APACHE

aurs:
  - description: "Based on Go modules, update a dependency to a major version."
    skip_upload: false
    homepage: https://github.com/ldez/motoko
    name: 'motoko-bin'
    provides:
      - motoko
    maintainers:
      - "Fernandez Ludovic <lfernandez dot dev at gmail dot com>"
    license: APACHE
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/motoko-bin.git"
    commit_author:
      name: ldez
      email: ldez@users.noreply.github.com
    package: |-
      # Bin
      install -Dm755 "./lego" "${pkgdir}/usr/bin/motoko"

      # License
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/motoko/LICENSE"

aur_sources:
  - description: "Based on Go modules, update a dependency to a major version."
    skip_upload: false
    homepage: https://github.com/ldez/motoko
    provides:
      - motoko
    maintainers:
      - "Fernandez Ludovic <lfernandez dot dev at gmail dot com>"
    license: APACHE
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/motoko.git"
    commit_author:
      name: ldez
      email: ldez@users.noreply.github.com
    build: |-
      export BUILD_DATE=$(date -u '+%Y-%m-%d_%I:%M:%S%p')
      
      export CGO_CPPFLAGS="${CPPFLAGS}"
      export CGO_CFLAGS="${CFLAGS}"
      export CGO_CXXFLAGS="${CXXFLAGS}"
      export CGO_LDFLAGS="${LDFLAGS}"
      export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
      
      go build -ldflags="-w -s -linkmode=external -X 'main.version=v${pkgver}' -X 'main.date=${BUILD_DATE}'"
      
      chmod +x "./${pkgname}"
    package: |-
      # Bin
      install -Dsm755 "./${pkgname}" "${pkgdir}/usr/bin/${pkgname}"
      
      # License
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
